name: wallet_online
version: 3.0.3+6
description: Wallet Online.
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies: 
  cupertino_icons: 1.0.4
  get: 4.6.1
  animated_splash_screen: 1.2.0
  flutter_spinkit: 5.1.0
  sqflite: 2.0.2
  fl_chart: 0.45.0
  intl: 0.17.0
  grouped_list: 4.2.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

