name: wallet_online
version: 5.0.0+8
description: Wallet Online.
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  get: 4.6.1
  cupertino_icons: 1.0.4
  animated_splash_screen: 1.2.0
  flutter_spinkit: 5.1.0
  sqflite: 2.0.2
  fl_chart: 0.45.0
  intl: 0.17.0
  grouped_list: 4.2.0
  flutter_speed_dial: 5.0.0+1
  iconly: 1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: app_icon_round
  image_path: assets/app_icon_round.png
  ios: true

flutter:
  assets:
    - assets/
  uses-material-design: true

